<?php
/**
 * Nischhal Portfolio Functions
 * 
 * 1. Theme Setup & Demo Content
 * 2. Enqueue Assets & Google Fonts
 * 3. Custom Post Types (Projects)
 * 4. Customizer API (The "Mega" Configuration)
 * 5. CSS Variable Injection
 */

// --- 1. THEME SETUP & DEMO CONTENT ---
function nischhal_theme_setup() {
    add_theme_support( 'title-tag' );
    add_theme_support( 'post-thumbnails' );
    add_theme_support( 'custom-logo', array( 'height' => 100, 'width' => 400, 'flex-height' => true, 'flex-width'  => true ) );
    add_theme_support( 'html5', array( 'search-form', 'gallery', 'caption', 'style', 'script' ) );
    add_theme_support( 'align-wide' );
    add_theme_support( 'responsive-embeds' );

    register_nav_menus( array(
        'primary' => __( 'Primary Menu', 'nischhal' ),
    ) );
}
add_action( 'after_setup_theme', 'nischhal_theme_setup' );

// Auto-seed content on activation
function nischhal_seed_content() {
    if ( get_option( 'nischhal_content_seeded' ) ) return;

    // 1. Seed Projects
    $projects = array(
        'Fintech Dashboard' => 'Enterprise banking solution reducing task time by 40%.',
        'Crypto Wallet' => 'Non-custodial wallet with seamless on-ramping.',
        'Design System v2' => 'Unified component library for a SaaS giant.',
        'HealthTech App' => 'Patient monitoring dashboard for clinicians.',
        'E-Commerce Redesign' => 'Boosting conversion rates through UX audits.',
        'Travel Booking API' => 'B2B integration platform for travel agents.',
        'Analytics Suite' => 'Real-time data visualization for marketing teams.',
        'Learning Platform' => 'Gamified LMS for corporate training.',
        'Logistics Tracker' => 'Last-mile delivery tracking interface.',
        'AI Content Tool' => 'Generative text editor for creators.'
    );

    foreach ($projects as $title => $excerpt) {
        if( !post_exists($title) ) {
            $post_id = wp_insert_post(array(
                'post_title' => $title,
                'post_content' => '<!-- wp:paragraph --><p>This is a demo project generated by the theme. You can edit this content in the WordPress Admin.</p><!-- /wp:paragraph -->',
                'post_excerpt' => $excerpt,
                'post_status' => 'publish',
                'post_type' => 'project'
            ));
            update_post_meta($post_id, 'project_year', '2025');
            update_post_meta($post_id, 'project_industry', 'Tech');
        }
    }

    // 2. Seed Blog Posts
    $blogs = array(
        'The Future of Design Systems' => 'Why code alignment is the next frontier.',
        'Navigating Enterprise UX' => 'Managing complexity without losing clarity.',
        'Web3 Interaction Patterns' => 'Trustless UI design principles.',
        'Accessibility is not a Checklist' => 'Building inclusive products from day one.',
        'Micro-interactions Matter' => 'How small details build user trust.',
        'Figma to React Workflow' => 'Streamlining developer handoff.',
        'Typography in UI' => 'Choosing the right type scale for data-heavy apps.',
        'Dark Mode Design' => 'Beyond just inverting colors.',
        'The ROI of UX' => 'Measuring design impact on business goals.',
        'AI in Product Design' => 'Curating vs Creating in the age of AI.'
    );

    foreach ($blogs as $title => $excerpt) {
        if( !post_exists($title) ) {
            wp_insert_post(array(
                'post_title' => $title,
                'post_content' => '<!-- wp:paragraph --><p>This is a demo article. Edit it to share your thoughts.</p><!-- /wp:paragraph -->',
                'post_excerpt' => $excerpt,
                'post_status' => 'publish',
                'post_type' => 'post'
            ));
        }
    }

    update_option( 'nischhal_content_seeded', true );
}
add_action( 'after_switch_theme', 'nischhal_seed_content' );

// --- 2. ENQUEUE ASSETS ---
function nischhal_enqueue_scripts() {
    // Dynamic Google Fonts Loader
    $h_font = get_theme_mod('typo_heading_font', 'Playfair Display');
    $b_font = get_theme_mod('typo_body_font', 'Inter');
    $fonts_url = 'https://fonts.googleapis.com/css2?family=' . urlencode($h_font) . ':wght@400;500;600&family=' . urlencode($b_font) . ':wght@300;400;500;600&display=swap';
    wp_enqueue_style( 'nischhal-google-fonts', $fonts_url, array(), null );

    wp_enqueue_style( 'main-style', get_stylesheet_uri(), array(), '18.0' );
    
    // Animation Libraries
    wp_enqueue_script( 'gsap', 'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js', array(), null, true );
    wp_enqueue_script( 'gsap-scrolltrigger', 'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js', array('gsap'), null, true );
    
    // Theme Logic
    wp_enqueue_script( 'theme-script', get_template_directory_uri() . '/js/main.js', array('gsap', 'gsap-scrolltrigger'), '18.0', true );
    
    // Pass Customizer Data to JS
    wp_localize_script( 'theme-script', 'themeConfig', array(
        'ajaxUrl'     => admin_url( 'admin-ajax.php' ),
        'enableMotion' => get_theme_mod('motion_enable', true),
        'animSpeed'    => get_theme_mod('motion_speed', 1.0),
        'cursorStyle'  => get_theme_mod('motion_cursor_style', 'dot'), // dot, ring, none
        'pageTrans'    => get_theme_mod('motion_page_trans', true),
        'waterEffect'  => get_theme_mod('motion_water_effect', false),
    ));
}
add_action( 'wp_enqueue_scripts', 'nischhal_enqueue_scripts' );

// --- 3. CPT: PROJECTS ---
function nischhal_register_projects() {
    register_post_type( 'project', array(
        'labels' => array( 'name' => 'Work', 'singular_name' => 'Project', 'menu_name' => 'Work (Projects)' ),
        'public' => true,
        'has_archive' => true,
        'menu_icon' => 'dashicons-art',
        'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt', 'custom-fields' ),
        'rewrite' => array( 'slug' => 'work' ),
        'show_in_rest' => true
    ));
    register_taxonomy( 'project_category', 'project', array(
        'labels' => array( 'name' => 'Categories' ),
        'hierarchical' => true,
        'show_in_rest' => true,
        'public' => true
    ));
}
add_action( 'init', 'nischhal_register_projects' );

// --- 4. THE MEGA CUSTOMIZER ---
function nischhal_customize_register( $wp_customize ) {
    
    // --- PANEL A: TYPOGRAPHY ---
    $wp_customize->add_panel( 'panel_typography', array( 'title' => 'Design: Typography', 'priority' => 20 ) );
    
    $wp_customize->add_section( 'sec_typo_fam', array( 'title' => 'Font Families', 'panel' => 'panel_typography' ) );
    $fonts = array( 'Inter' => 'Inter', 'Playfair Display' => 'Playfair Display', 'Space Grotesk' => 'Space Grotesk', 'DM Sans' => 'DM Sans', 'Roboto' => 'Roboto', 'Lora' => 'Lora' );
    
    $wp_customize->add_setting( 'typo_heading_font', array( 'default' => 'Playfair Display' ) );
    $wp_customize->add_control( 'typo_heading_font', array( 'label' => 'Heading Font', 'section' => 'sec_typo_fam', 'type' => 'select', 'choices' => $fonts ) );
    
    $wp_customize->add_setting( 'typo_body_font', array( 'default' => 'Inter' ) );
    $wp_customize->add_control( 'typo_body_font', array( 'label' => 'Body Font', 'section' => 'sec_typo_fam', 'type' => 'select', 'choices' => $fonts ) );

    $wp_customize->add_section( 'sec_typo_sizes', array( 'title' => 'Sizes & Scale', 'panel' => 'panel_typography' ) );
    
    // Heading Scale
    $wp_customize->add_setting( 'h1_size_desktop', array( 'default' => '4rem' ) );
    $wp_customize->add_control( 'h1_size_desktop', array( 'label' => 'H1 Desktop', 'section' => 'sec_typo_sizes', 'type' => 'text' ) );
    $wp_customize->add_setting( 'h1_size_mobile', array( 'default' => '2.5rem' ) );
    $wp_customize->add_control( 'h1_size_mobile', array( 'label' => 'H1 Mobile', 'section' => 'sec_typo_sizes', 'type' => 'text' ) );

    // Body Scale
    $wp_customize->add_setting( 'body_size', array( 'default' => '1.125rem' ) );
    $wp_customize->add_control( 'body_size', array( 'label' => 'Body Size', 'section' => 'sec_typo_sizes', 'type' => 'text' ) );

    // --- PANEL B: COLORS (Light/Dark) ---
    $wp_customize->add_panel( 'panel_colors', array( 'title' => 'Design: Colors', 'priority' => 21 ) );
    
    // Dark Mode (Default)
    $wp_customize->add_section( 'sec_colors_dark', array( 'title' => 'Dark Theme Tokens', 'panel' => 'panel_colors' ) );
    $d_colors = array(
        'dark_bg' => '#050505', 'dark_surface' => '#0a0a0a', 'dark_card' => '#111111', 
        'dark_text_main' => '#FFFFFF', 'dark_text_muted' => '#A1A1AA', 'dark_accent' => '#3B82F6', 'dark_border' => 'rgba(255,255,255,0.08)'
    );
    foreach($d_colors as $k => $v) {
        $wp_customize->add_setting( $k, array( 'default' => $v, 'transport' => 'postMessage' ) );
        $wp_customize->add_control( new WP_Customize_Color_Control( $wp_customize, $k, array( 'label' => ucfirst(str_replace('_', ' ', $k)), 'section' => 'sec_colors_dark' ) ) );
    }

    // Light Mode
    $wp_customize->add_section( 'sec_colors_light', array( 'title' => 'Light Theme Tokens', 'panel' => 'panel_colors' ) );
    $l_colors = array(
        'light_bg' => '#F7F9FC', 'light_surface' => '#FFFFFF', 'light_card' => '#FFFFFF', 
        'light_text_main' => '#0f172a', 'light_text_muted' => '#64748b', 'light_accent' => '#2563EB', 'light_border' => 'rgba(0,0,0,0.08)'
    );
    foreach($l_colors as $k => $v) {
        $wp_customize->add_setting( $k, array( 'default' => $v, 'transport' => 'postMessage' ) );
        $wp_customize->add_control( new WP_Customize_Color_Control( $wp_customize, $k, array( 'label' => ucfirst(str_replace('_', ' ', $k)), 'section' => 'sec_colors_light' ) ) );
    }

    // --- PANEL C: LAYOUT & GRID ---
    $wp_customize->add_panel( 'panel_layout', array( 'title' => 'Design: Layout & Grid', 'priority' => 22 ) );
    $wp_customize->add_section( 'sec_grid', array( 'title' => 'Background Grid', 'panel' => 'panel_layout' ) );
    
    $wp_customize->add_setting( 'grid_opacity', array( 'default' => '0.05', 'transport' => 'postMessage' ) );
    $wp_customize->add_control( 'grid_opacity', array( 'label' => 'Grid Opacity', 'section' => 'sec_grid', 'type' => 'range', 'input_attrs' => array( 'min' => 0, 'max' => 0.5, 'step' => 0.01 ) ) );
    
    $wp_customize->add_setting( 'grid_size', array( 'default' => '60', 'transport' => 'postMessage' ) );
    $wp_customize->add_control( 'grid_size', array( 'label' => 'Cell Size (px)', 'section' => 'sec_grid', 'type' => 'number' ) );

    // --- PANEL D: HOME BUILDER ---
    $wp_customize->add_panel( 'panel_home', array( 'title' => 'Page: Home Builder', 'priority' => 30 ) );
    
    // Hero
    $wp_customize->add_section( 'sec_home_hero', array( 'title' => 'Hero Section', 'panel' => 'panel_home' ) );
    $wp_customize->add_setting( 'hero_h1_line1', array( 'default' => 'Crafting scalable', 'transport' => 'postMessage' ) );
    $wp_customize->add_control( 'hero_h1_line1', array( 'label' => 'Headline Line 1', 'section' => 'sec_home_hero', 'type' => 'text' ) );
    $wp_customize->add_setting( 'hero_h1_line2', array( 'default' => 'digital products.', 'transport' => 'postMessage' ) );
    $wp_customize->add_control( 'hero_h1_line2', array( 'label' => 'Headline Line 2', 'section' => 'sec_home_hero', 'type' => 'text' ) );
    
    $wp_customize->add_setting( 'hero_img', array( 'default' => 'https://i.imgur.com/ixsEpYM.png' ) );
    $wp_customize->add_control( new WP_Customize_Image_Control( $wp_customize, 'hero_img', array( 'label' => 'Hero Image', 'section' => 'sec_home_hero' ) ) );

    // Ticker
    $wp_customize->add_section( 'sec_home_ticker', array( 'title' => 'Skills Ticker', 'panel' => 'panel_home' ) );
    $wp_customize->add_setting( 'ticker_items', array( 'default' => 'Design Systems, Enterprise UX, Web3, Strategy', 'sanitize_callback' => 'sanitize_text_field' ) );
    $wp_customize->add_control( 'ticker_items', array( 'label' => 'Items (comma separated)', 'section' => 'sec_home_ticker', 'type' => 'textarea' ) );

    // Testimonials
    $wp_customize->add_section( 'sec_testimonials', array( 'title' => 'Testimonials', 'panel' => 'panel_home' ) );
    for($i=1; $i<=3; $i++) {
        $wp_customize->add_setting( "testim_{$i}_quote", array( 'default' => '' ) );
        $wp_customize->add_control( "testim_{$i}_quote", array( 'label' => "Quote #$i", 'section' => 'sec_testimonials', 'type' => 'textarea' ) );
        $wp_customize->add_setting( "testim_{$i}_auth", array( 'default' => '' ) );
        $wp_customize->add_control( "testim_{$i}_auth", array( 'label' => "Author #$i", 'section' => 'sec_testimonials', 'type' => 'text' ) );
    }

    // --- PANEL E: MOTION & EFFECTS ---
    $wp_customize->add_panel( 'panel_motion', array( 'title' => 'Motion & Effects', 'priority' => 100 ) );
    $wp_customize->add_section( 'sec_motion_global', array( 'title' => 'Global Settings', 'panel' => 'panel_motion' ) );
    
    $wp_customize->add_setting( 'motion_enable', array( 'default' => true, 'sanitize_callback' => 'wp_validate_boolean' ) );
    $wp_customize->add_control( 'motion_enable', array( 'label' => 'Enable Animations', 'section' => 'sec_motion_global', 'type' => 'checkbox' ) );
    
    $wp_customize->add_setting( 'motion_page_trans', array( 'default' => true, 'sanitize_callback' => 'wp_validate_boolean' ) );
    $wp_customize->add_control( 'motion_page_trans', array( 'label' => 'Page Transitions (Curtain)', 'section' => 'sec_motion_global', 'type' => 'checkbox' ) );

    $wp_customize->add_setting( 'motion_cursor_style', array( 'default' => 'dot' ) );
    $wp_customize->add_control( 'motion_cursor_style', array( 'label' => 'Cursor Style', 'section' => 'sec_motion_global', 'type' => 'select', 'choices' => array('none'=>'Native', 'dot'=>'Dot & Ring') ) );

    $wp_customize->add_setting( 'motion_speed', array( 'default' => 1.0 ) );
    $wp_customize->add_control( 'motion_speed', array( 'label' => 'Animation Speed Multiplier', 'section' => 'sec_motion_global', 'type' => 'number', 'input_attrs' => array('min'=>0.5, 'max'=>2.0, 'step'=>0.1) ) );

}
add_action( 'customize_register', 'nischhal_customize_register' );

// --- 5. CSS VARIABLE INJECTION ---
function nischhal_customizer_css() {
    ?>
    <style type="text/css">
        :root {
            /* TYPOGRAPHY */
            --font-serif: "<?php echo get_theme_mod('typo_heading_font', 'Playfair Display'); ?>", serif;
            --font-sans: "<?php echo get_theme_mod('typo_body_font', 'Inter'); ?>", sans-serif;
            --h1-d: <?php echo get_theme_mod('h1_size_desktop', '4rem'); ?>;
            --h1-m: <?php echo get_theme_mod('h1_size_mobile', '2.5rem'); ?>;
            --body-s: <?php echo get_theme_mod('body_size', '1.125rem'); ?>;

            /* GRID */
            --grid-opacity: <?php echo get_theme_mod('grid_opacity', '0.05'); ?>;
            --grid-size: <?php echo get_theme_mod('grid_size', '60'); ?>px;

            /* DARK THEME */
            --bg-root: <?php echo get_theme_mod('dark_bg', '#050505'); ?>;
            --bg-surface: <?php echo get_theme_mod('dark_surface', '#0a0a0a'); ?>;
            --bg-card: <?php echo get_theme_mod('dark_card', '#111111'); ?>;
            --text-primary: <?php echo get_theme_mod('dark_text_main', '#FFFFFF'); ?>;
            --text-secondary: <?php echo get_theme_mod('dark_text_muted', '#A1A1AA'); ?>;
            --accent-blue: <?php echo get_theme_mod('dark_accent', '#3B82F6'); ?>;
            --border-faint: <?php echo get_theme_mod('dark_border', 'rgba(255,255,255,0.08)'); ?>;
        }

        [data-theme="light"] {
            /* LIGHT THEME */
            --bg-root: <?php echo get_theme_mod('light_bg', '#F7F9FC'); ?>;
            --bg-surface: <?php echo get_theme_mod('light_surface', '#FFFFFF'); ?>;
            --bg-card: <?php echo get_theme_mod('light_card', '#FFFFFF'); ?>;
            --text-primary: <?php echo get_theme_mod('light_text_main', '#0f172a'); ?>;
            --text-secondary: <?php echo get_theme_mod('light_text_muted', '#64748b'); ?>;
            --accent-blue: <?php echo get_theme_mod('light_accent', '#2563EB'); ?>;
            --border-faint: <?php echo get_theme_mod('light_border', 'rgba(0,0,0,0.08)'); ?>;
        }
    </style>
    <?php
}
add_action( 'wp_head', 'nischhal_customizer_css' );

// Post Helpers
function get_project_cat_slugs($post_id) {
    $terms = get_the_terms($post_id, 'project_category');
    if ($terms && !is_wp_error($terms)) {
        $slugs = array();
        foreach ($terms as $term) $slugs[] = $term->slug;
        return implode(' ', $slugs);
    }
    return '';
}
?>